---
title: ''
output: html_document
---

## Questions on Paul Lewis phylogenetics primer part 1 -- Trees and likelihood


> 1. In your own words, how would you describe the terms **conditional probability** and **likelihood**?

> 2. Why do we calculate likelihoods on a log scale?

> 3. How does the probability of transitioning from one character state to another (e.g. from A to T) change over time? You can use the [Transition probability tool](https://plewis.github.io/applets/jc-transition-probabilities/) to explore this further. 

> 4. **Felsenstein’s pruning algorithm** 
    a. What do we need this for? / What do we calculate using this?
    b. Can you describe the gist of Felsenstein’s pruning algorithm? (advanced)

## Notes

*For a good description of Felsenstein's pruning algorithm check out [Section 8.8](https://lukejharmon.github.io/pcm/chapter8_fitdiscrete/#section-8.8-appendix-felsensteins-pruning-algorithm) of this great online book [Phylogenetic Comparative Methods](https://lukejharmon.github.io/pcm/) by Luke Harmon.*

*We won't really encounter multifurcating trees in the rest of this course. This is because they're not directly output by any of the software we'll use. However, we'll talk about how to represent uncertainty in the trees we generate.*

