---
title: "Schedule"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\

Course material will be uploaded here throughout the semester!

# Rough Schedule

* Course introduction and Parsimony 28.04
* Likelihood and substitution models 05.05
* No Class (Paul Lewis's seminars) 12.05
* Bayesian tree inference 19.05
* Clock models 26.05
* Tree models 02.06
* Model selection 09.06
* Diversification rate estimation with Joëlle Barido-Sottani 16.06

# Week 1 materials

```{r, echo = FALSE}
library(kableExtra)
#urls <- c("slides/day-01.html",NA,NA,"slides/day-01.html#26",NA,NA,"slides/revisiting-statistics.pdf")

urls <- c(NA,NA)

dt <- data.frame(schedule = c("Course introduction"),
                 topics = c("tree thinking, parsimony, statistical consistency"))
#dt$schedule[1] <- paste0("[", dt$schedule[1], "](", urls[1], ")")
#dt$schedule[4] <- paste0("[", dt$schedule[4], "](", urls[4], ")")
#dt$schedule[7] <- paste0("[", dt$schedule[7], "](", urls[7], ")")
kbl(dt) %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")

#Further reading:

#* [Learning statistics with R: Chapter 1 and Chapter 11](https://learningstatisticswithr.com/book/why-do-we-learn-statistics.html)
#* [tinystats.github.io/teacups-giraffes-and-statistics](https://tinystats.github.io/teacups-giraffes-and-statistics/)
```




